relativeURLs: true
uglyURLs: true
languageCode: en-us
title: IIIF Technical Workshop
theme: hugo-theme-learn
canonifyURLs: true

outputs:
  home: [ "HTML", "RSS", "JSON"]

params:
  author: Jason Ronallo
  description: IIIF Technical Workshop
  editURL: https://github.com/jronallo/iiif-workshop-new/edit/master/content/
  themeVariant: green
  disableSearch: false
  disableInlineCopyToClipBoard: true
  showVisitedLinks: true

menu:
  shortcuts:
    - name: Mirador
      url: "/viewers/mirador.html"
      weight: 1
    - name: Universal Viewer
      url: "/viewers/uv.html"
      weight: 1
    - name: Feedback
      url: "/links/feedback.html"
      weight: 10
    - name: Credits
      url: "/links/credits.html"
      weight: 20
    - name: License
      url: "/links/license.html"
      weight: 30
    # - name: Instructor's Guide
    #   url: "/links/instructors-guide.html"
    #   weight: 1000
