baseURL: https://ronallo.com/iiif-workshop-new/
languageCode: en-us
title: IIIF Technical Workshop
theme: hugo-theme-learn
canonifyURLs: true

outputs:
  home: [ "HTML", "RSS", "JSON"]

params:
  themeVariant: green

menu:
  shortcuts:
    - name: Mirador
      url: "viewers/mirador.html"
      weight: 1
    - name: Feedback
      url: "links/feedback"
      weight: 10
    - name: Credits
      url: "links/credits"
      weight: 20
    - name: License
      url: "links/license"
      weight: 30
